name: unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: lint
      run: CHECK_FORMAT=1 ./run_clang_format.sh
      continue-on-error: true

    - name: run unit tests
      run: docker build . -t iso14229 && docker run --cap-add NET_ADMIN --rm -v $(pwd):$(pwd) -w $(pwd) iso14229 bazel test //test:all 

